services:
  - type: web
    name: tb-beauty-backend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYTABS_PROFILE_ID
        sync: false
      - key: PAYTABS_SERVER_KEY
        sync: false
